import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:harmfilter_flutter/models/post_model.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:harmfilter_flutter/models/user_profile.dart';

class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Users Collection
  CollectionReference get _usersRef => _db.collection('users');

  // Posts Collection
  CollectionReference get _postsRef => _db.collection('posts');

  // Reports Collection
  CollectionReference get _reportsRef => _db.collection('reports');

  // Initialize user profile on first login
  Future<void> initializeUserProfile(User user) async {
    try {
      final userDoc = _usersRef.doc(user.uid);
      final docSnapshot = await userDoc.get();

      if (!docSnapshot.exists) {
        // New user
        await userDoc.set({
          'uid': user.uid,
          'email': user.email,
          'displayName': user.displayName ?? user.email?.split('@').first ?? 'User',
          'avatarUrl': user.photoURL ?? '',
          'points': 0,
          'joinedAt': Timestamp.fromDate(DateTime.now()),
          'lastActivityDate': Timestamp.fromDate(DateTime.now()),
        });
      }
    } catch (e) {
      debugPrint('Error initializing user profile: $e');
    }
  }

  // Update user points
  Future<void> updateUserPoints(String uid, int points) async {
    try {
      await _usersRef.doc(uid).update({
        'points': points,
        'lastActivityDate': Timestamp.fromDate(DateTime.now()),
      });
    } catch (e) {
      debugPrint('Error updating user points: $e');
      rethrow;
    }
  }

  // Stream all posts (for Feed)
  Stream<List<PostModel>> getPostsStream() {
    return _postsRef
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PostModel.fromFirestore(doc))
          .toList();
    });
  }

  // Stream user's posts (for Profile)
  Stream<List<PostModel>> getUserPostsStream(String uid) {
    return _postsRef
        .where('userId', isEqualTo: uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => PostModel.fromFirestore(doc))
          .toList();
    });
  }

  // Add a new post
  Future<void> addPost(
    String text, {
    String? imageUrl,
    String label = 'normal',
    double fusedScore = 0.0,
    String? extractedImageText,
  }) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception('Must be logged in to post');
    }

    final postData = PostModel(
      id: '', // Will be generated by Firestore
      userId: user.uid,
      username: user.displayName ?? user.email?.split('@').first ?? 'User',
      avatar: user.photoURL ?? '',
      text: text,
      label: label,
      fusedScore: fusedScore,
      imageUrl: imageUrl,
      createdAt: DateTime.now(),
    );

    try {
      final firestoreMap = postData.toFirestore();
      // Store OCR extracted text alongside the post if present
      if (extractedImageText != null && extractedImageText.isNotEmpty) {
        firestoreMap['extractedImageText'] = extractedImageText;
      }
      await _postsRef.add(firestoreMap);
    } catch (e) {
      debugPrint('Error adding post: $e');
      rethrow;
    }
  }

  Stream<PostModel?> getPostByIdStream(String postId) {
    return _postsRef.doc(postId).snapshots().map((doc) {
      if (!doc.exists) return null;
      return PostModel.fromFirestore(doc);
    });
  }

  Future<void> deletePost(String postId) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception('User not authenticated');
    }

    final postRef = _postsRef.doc(postId);
    final postSnapshot = await postRef.get();
    if (!postSnapshot.exists) {
      throw Exception('Post not found');
    }

    final data = postSnapshot.data() as Map<String, dynamic>? ?? {};
    if (data['userId'] != user.uid) {
      throw Exception('You can only delete your own posts');
    }

    await postRef.delete();
  }

  Future<void> submitPostReport({
    required String postId,
    required String postContent,
    required String currentFlag,
    required String reportedAs,
  }) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception('User not authenticated');
    }

    await _reportsRef.add({
      'postId': postId,
      'postContent': postContent,
      'currentFlag': currentFlag,
      'reportedAs': reportedAs,
      'reportedBy': user.uid,
      'reportedAt': FieldValue.serverTimestamp(),
      'status': 'pending',
    });
  }

  Future<UserProfile?> getCurrentUserProfile() async {
    final user = _auth.currentUser;
    if (user == null) return null;
    final doc = await _usersRef.doc(user.uid).get();
    if (!doc.exists) return null;
    return UserProfile.fromFirestore(doc);
  }

  Future<void> updateCurrentUserProfile({
    required String displayName,
    required String bio,
    required String website,
  }) async {
    final user = _auth.currentUser;
    if (user == null) throw Exception('User not authenticated');

    await _usersRef.doc(user.uid).set({
      'displayName': displayName,
      'bio': bio,
      'website': website,
      'updatedAt': Timestamp.fromDate(DateTime.now()),
    }, SetOptions(merge: true));

    if ((user.displayName ?? '') != displayName) {
      await user.updateDisplayName(displayName);
    }
  }

  Future<Map<String, dynamic>> getCurrentUserQuizProgress() async {
    final user = _auth.currentUser;
    if (user == null) return {};

    final doc = await _usersRef.doc(user.uid).get();
    if (!doc.exists) return {};

    final data = doc.data() as Map<String, dynamic>?;
    final progress = data?['quizProgress'];
    if (progress is Map<String, dynamic>) {
      return progress;
    }
    return {};
  }

  Future<void> saveQuizResult({
    required String quizId,
    required int score,
    required int totalPoints,
    required int awardPoints,
  }) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception('User not authenticated');
    }

    await _db.runTransaction((transaction) async {
      final userRef = _usersRef.doc(user.uid);
      final snapshot = await transaction.get(userRef);
      final data = snapshot.data() as Map<String, dynamic>? ?? {};
      final progress = Map<String, dynamic>.from(data['quizProgress'] ?? {});
      final currentQuiz = Map<String, dynamic>.from(progress[quizId] ?? {});

      final percentage = totalPoints <= 0 ? 0 : ((score / totalPoints) * 100).round();
      final passed = percentage >= 80;
      final alreadyAwarded = (currentQuiz['passed'] ?? false) == true;
      final pointsToAdd = (passed && !alreadyAwarded) ? awardPoints : 0;

      progress[quizId] = {
        'score': score,
        'totalPoints': totalPoints,
        'percentage': percentage,
        'passed': passed,
        'awardedPoints': pointsToAdd,
        'completedAt': FieldValue.serverTimestamp(),
      };

      final updatePayload = <String, dynamic>{
        'quizProgress': progress,
        'lastActivityDate': FieldValue.serverTimestamp(),
      };

      if (pointsToAdd > 0) {
        updatePayload['points'] = FieldValue.increment(pointsToAdd);
      }

      transaction.set(userRef, updatePayload, SetOptions(merge: true));
    });
  }
}
